### ISSUE TITLE
Don't use Discord for support.

### ISSUE THREAD

**Issue by Generator** [berty/community#106]
Discord is a well known privacy nightmare, makes no sense using it for support on a "privacy-first messaging app".

Consider a better alternative, like Matrix, IRC, XMPP ...

- [Reasons not to use the Discord communications system](https://stallman.org/discord.html)  
- [Discord — Spyware Watchdog](https://spyware.neocities.org/articles/discord.html)

**Comment by Jorropo** [comment]
Thx for your issue :) We don't use discord for support, we don't have any users yet so no support to make yet.

With more words :) Nobody should use berty right now (accounts get corrupted sometimes, the app might decide to stop working for the next 15 minutes, the ui is broken on Android, there is no true GUI on desktop (you have either dev tools or an `Irssi` like UI)) appart for devs and for peoples using it just to test, sending a few messages. So as we don't have any users yet we shouldn't have any support to make yet.

But thx, I might setup a Discord, Matrix, IRC, ... bridge for the open beta.

**Comment by xuhcc** [comment]
There is a matrix room #berty:matrix.org
It is bridged to discord

**Comment by pierreboc** [comment]
Hey!

Thank you for reaching us. 

@Generator : We answered your question in more detail in a larger issue (#108 ). In short, we do NOT use Discord for support purposes but for convenience - to connect the community easily and quickly. 

@xuhcc : FYI, The bridge is currently disabled. We prefer to centralize exchanges with the early community on this Discord.

Best,
