### ISSUE TITLE
"Messaging Alternatives", a comparison tool

### ISSUE THREAD

**Issue by moul** [berty/community#67]
It's natural than some of our most asked questions are things like `"what's your difference with [INSERT ANOTHER APP HERE]"`

We think that the best way to reply openly and transparently is to write it once for good, allow anyone to update the information, in particular, the developers of the alternative itself.

The needs are:
* to be editable by anyone
* to have two views,
    * one for "Berty Chat" that will list alternative messaging apps, and
    * one for "Berty Protocol" that will contain alternative P2P libraries
* to be easily readable, especially for non-tech

---

Our current idea is to create a dedicated repo focused on allowing people to add/edit alternatives, probably .yml files

Then to integrate it somewhere automatically, i.e., on our website or a dedicated domain, if it makes more sense

---

Very cool examples:

* https://www.eff.org/fr/pages/secure-messaging-scorecard
* https://www.securemessagingapps.com/

Ideally, we should be listed on existing tools, but the first one is not maintained anymore, and the second one will probably not accept apps that are still in development

---

Feedback is much appreciated <3

**Comment by fte378** [comment]
If the tools are centralised the Terms of Use should be evaluated if they value privacy.
For example Threema and WhatsApp may have many similarities but the Terms of use differ significantly.

**Comment by fte378** [comment]
What about a collection of markdown files (one for every tool) where the table is generated from Frontmatter variables then?

**Comment by cdeleeuwe** [comment]
@fte378 sounds good. I think we could use a headless bundle (https://gohugo.io/content-management/page-bundles/#headless-bundle), and use the Frontmatter variables for each tool as you suggested.

Not sure where to host it, but we could integrate it directly on our website and add an "Edit on Github" link for each row/tool. @moul what do you think?

**Comment by moul** [comment]
let's go with that 👍

**Comment by moul** [comment]
initial version is now available here: https://berty.tech/faq

![Manfreds-iMac - Screen Shot 2020-06-17 at 13 30 58](https://user-images.githubusercontent.com/94029/84892971-c8e51880-b09e-11ea-85ff-b8558e09d879.png)

lets people help us complete this table :) 🙏

note: if the current fields/possible-values are too limiting, do not hesitate to ping us so we can improve the tool to help to have accurate answers

**Comment by moul** [comment]
oh and feel free to add "bad points" for berty, we made multiple hard choices (p2p, privacy-first, etc), with those constraints we can't be green everywhere
